### ISSUE TITLE
Every commands output is captured and needs exiting

### ISSUE THREAD

**Issue by vindarel** [deftask/deftask-cli#1]
Hello !
Every command doesn't simply print on stdout, the output is captured by a terminal app (like `less`), and we need to press `q` to exit. It is particularly annoying and useless with an error: I run 

    deftask project-config

I see

![selection_265](https://user-images.githubusercontent.com/3721004/50859052-8c35cd80-1392-11e9-975f-f757e11acaa3.png)

and after `q`:

```
$ ./deftask project-config                                
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10005305B3}>:
  No project-id given

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005305B3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "No project-id given" {1003EC7003}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "No project-id given" {1003EC7003}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "No project-id given" {1003EC7003}>)
3: (ERROR "No project-id given")
4: (DEFTASK-CLI::COMMAND-PROJECT-CONFIG ("project-config"))
5: (DEFTASK-CLI::HANDLE-COMMAND :PROJECT-CONFIG ("project-config"))
6: (DEFTASK-CLI:MAIN)
7: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
8: ((FLET "WITHOUT-INTERRUPTS-BODY-27" :IN SAVE-LISP-AND-DIE))
9: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
```

(which btw isn't so nice to see for this simple error :S )

regards

**Comment by chaitanyagupta** [comment]
1. Regarding output being piped to `less`, you can fix it by either setting the `PAGER` environment variable to `cat`, or you can set it in the deftask config: `deftask config pager cat`. I will also clarify this in the README and help commands.

2. Seeing the backtrace is a really bad user experience, my apologies! I will fix it asap.

**Comment by chaitanyagupta** [comment]
@vindarel can you tell me a bit more about your environment?

By default, if the `PAGER` environment variable or the deftask config value is not set, deftask uses `less -FRX` to page the output. The `-F` option causes `less` to quit if the entire output can be shown in one screen. Which means you should not have seen that empty screen with no output.

I am guessing either your `PAGER` is already set to something, or you are using a version of `less` that doesn't support `-F`. 

Can you tell me what happens if you run `PAGER="less -FRX" deftask project-config`?

**Comment by vindarel** [comment]
running this it works fine, I see the output straight away.

My pager is set to `less` and I have `export LESS='-R'`.

**Comment by chaitanyagupta** [comment]
Thanks for the info. I will figure out how to handle this issue more gracefully.

**Comment by chaitanyagupta** [comment]
I've created a new release [v0.2.3](https://github.com/deftask/deftask-cli/releases/tag/v0.2.3) that will suppress the backtrace and improve error handling in general. 

As far as the handling of the pager goes, let me think a bit more. As much as possible I'd like to avoid showing the user a blank screen from `less` when errors occur.

**Comment by chaitanyagupta** [comment]
> As far as the handling of the pager goes, let me think a bit more. As much as possible I'd like to avoid showing the user a blank screen from less when errors occur.

I was looking into this and I believe that with the improved error handling, all error messages are also sent to the pager. So closing this. If the bug still occurs (with v0.2.3), please feel free to re-open this.
